In [7]:
import numpy as np
print(np)
print(np.__version__)

<module 'numpy' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.19.2


In [9]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
print(a.ndim)
print('ndim:',a.ndim)
print('shape:',a.shape)
print('size:',a.size)
print('dtype:',a.dtype)
print('itemsize:',a.itemsize)
print('data:',a.data)

2
ndim: 2
shape: (3, 5)
size: 15
dtype: int64
itemsize: 8
data: <memory at 0x7f85ad80ca00>


In [21]:
print('list(a):',list(a))
print('tolist():',a.tolist())

list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [22]:
#1簡答題
print('list(a)') #只轉第一層為list
print('a.tolist()') #全部都轉list

list(a)
a.tolist()


In [31]:
#2
a = np.random.randint(10, size=6)
print(a)
print('ndim:',a.ndim)
print('shape:',a.shape)
print('size:',a.size)
print('dtype:',a.dtype)
print('itemsize:',a.itemsize)
print('length:',len(a))
print('type:',type(a))

[4 1 2 2 8 9]
ndim: 1
shape: (6,)
size: 6
dtype: int64
itemsize: 8
length: 6
type: <class 'numpy.ndarray'>


In [32]:
b = np.random.randint(10, size=(3,4))
print(b)
print('ndim:',b.ndim)
print('shape:',b.shape)
print('size:',b.size)
print('dtype:',b.dtype)
print('itemsize:',b.itemsize)
print('length:',len(b))
print('type:',type(b))

[[0 8 6 8]
 [0 5 1 5]
 [9 4 9 3]]
ndim: 2
shape: (3, 4)
size: 12
dtype: int64
itemsize: 8
length: 3
type: <class 'numpy.ndarray'>


In [33]:
c = np.random.randint(10, size=(2,3,2))
print(c)
print('ndim:',c.ndim)
print('shape:',c.shape)
print('size:',c.size)
print('dtype:',c.dtype)
print('itemsize:',c.itemsize)
print('length:',len(c))
print('type:',type(c))

[[[8 8]
  [7 2]
  [8 9]]

 [[8 1]
  [8 9]
  [5 3]]]
ndim: 3
shape: (2, 3, 2)
size: 12
dtype: int64
itemsize: 8
length: 2
type: <class 'numpy.ndarray'>


In [34]:
#3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
print(a.tolist())
print(list(a))

[4, 1, 2, 2, 8, 9]
[4, 1, 2, 2, 8, 9]


In [35]:
print(b.tolist())
print(list(b))

[[0, 8, 6, 8], [0, 5, 1, 5], [9, 4, 9, 3]]
[array([0, 8, 6, 8]), array([0, 5, 1, 5]), array([9, 4, 9, 3])]


In [36]:
print(c.tolist())
print(list(c))

[[[8, 8], [7, 2], [8, 9]], [[8, 1], [8, 9], [5, 3]]]
[array([[8, 8],
       [7, 2],
       [8, 9]]), array([[8, 1],
       [8, 9],
       [5, 3]])]


In [42]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a=np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [43]:
#2.呈上題，將以上數列取出偶數。
a[0:21:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [44]:
#3.呈1題，將數列取出3的倍數。
a[0:21:3]

array([ 0,  3,  6,  9, 12, 15, 18])