In [1]:
import numpy as np
print(np)
print(np .__version__)

<module 'numpy' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.19.2


In [7]:
a=np.arange(15).reshape(3,5)
print(a)
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
print(a.dtype)
print(a.itemsize)

int64
8


In [12]:
print(a.dtype=='int64')
print(a.dtype is 'int64')
print(a.dtype is np.int64)

True
False
False


<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-12-e509eadd05e8>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a.dtype is 'int64')


In [17]:
print(a.dtype=='int64')
print(a.dtype==np.int64)
print(a.dtype is np.dtype('int64'))

True
True
True


In [21]:
#[簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
print('type(a): ', type(a))#查看a類型
print('a.dtype: ', a.dtype)#a的資料型態

type(a):  <class 'numpy.ndarray'>
a.dtype:  int64


In [31]:
#2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。
import numpy as np
def is_dtype(a, t):
    return a.dtype is np.dtype(t)
a = np.random.randint(10, size=6) 
print(a)

print(is_dtype(a,'int')) 
print(is_dtype(a,np.int)) 
print(is_dtype(a,np.dtype('int')))

[5 2 3 9 7 4]
True
True
True


In [32]:
#3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？
def is_dtype(a, t):
    return a.dtype is t
# is屬於強比較，必須要兩邊所有規格都相同。
# 若是要判斷元素的資料型別是否相等，則需要與np.dtype物件相比
def is_dtype(a, t):
    return type(a) == np.dtype(t)
# type(...)為返回引數的資料型別，並非陣列內元素的資料型別
def is_dtype(a, t):
    return type(a) is np.dtype(t)
# type(...)為返回引數的資料型別，並非陣列內元素的資料型別


In [33]:
#題目：array1 = np.array(range(30))
#1將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")



In [ ]:
#2呈上題的 array，找出被 6 除餘 1 的數的索引